### ISSUE TITLE
[1.20.1] Setting respawnHealth inoperate

### ISSUE THREAD

**Issue by SigmaFlame** [Terrails/stat-tinkerer#1]
Setting 'respawnHealth' is inoperate.
Trying to set respawnHealth = 1 doesn't change the player Health to 1 when he dead, but he has full life instead.

**Comment by Terrails** [comment]
There seems to be no issue with this using the latest version. Please make sure that you are using the correct config file. With Forge, you have to use the file in `saves/world/serverconfig` of each world. Every other modloader (fabric and quilt) use the file in `config` folder.

**Comment by SigmaFlame** [comment]
I found that it's the mod Twilight's Flavors & Delight that makes your mod not functional.
Cuisine Delight also breaks your mod, and probably all the other mods from the same author as well.

**Comment by lcy0x1** [comment]
You can disable this in config:
in `l2configs/l2library-common.toml`, set
`restoreFullHealthOnRespawn = false`

I add that because my mods have curios that adds max health, and MaxHealthFix cannot fix that because curios load attributes after first player tick.

**Comment by SigmaFlame** [comment]
Thanks, it works, but now, it's the mod Aether that breaks this mod.
